USE [TotDB]
IF OBJECT_ID('dbo.HistoryTotalsMT', 'U') IS NULL
    BEGIN
		CREATE TABLE [dbo].[HistoryTotalsMT]
		(
			[tirazhi] [nvarchar](255) NULL,
			[data] [datetime] NULL,
			[dzhek] [numeric](9, 5) NULL,
			[pul] [numeric](9, 5) NULL,
			[slozhn] [numeric](9, 5) NULL,
			[maks_vin] [numeric](9, 5) NULL,
			[kol_var] [int] NULL,
			[kol_unik] [int] NULL,
			[ver_vin_dzhek] [numeric](9, 5) NULL,
			[kol_8] [int] NULL,
			[sum_8] [numeric](9, 5) NULL,
			[rez_8] [numeric](9, 5) NULL,
			[kol_7] [int] NULL,
			[sum_7] [numeric](9, 5) NULL,
			[rez_7] [numeric](9, 5) NULL,
			[kol_6] [int] NULL,
			[sum_6] [numeric](9, 5) NULL,
			[rez_6] [numeric](9, 5) NULL,
			[kol_5] [int] NULL,
			[sum_5] [numeric](9, 5) NULL,
			[rez_5] [numeric](9, 5) NULL,
			[kol_4] [int] NULL,
			[sum_4] [numeric](9, 5) NULL,
			[rez_4] [numeric](9, 5) NULL,
			[kol_3] [int] NULL,
			[sum_3] [numeric](9, 5) NULL,
			[rez_3] [numeric](9, 5) NULL,
			[kol_2] [int] NULL,
			[sum_2] [numeric](9, 5) NULL,
			[rez_2] [numeric](9, 5) NULL,
			[sob] [int] NULL,
			[razdel] [nvarchar](255) NULL,
			[match] [nvarchar](255) NULL,
			[schet] [nvarchar](10) NULL,
			[isxod] [nvarchar](10) NULL,
			[ver10] [numeric](9, 2) NULL,
			[pul10] [numeric](9, 2) NULL,
			[ver20] [numeric](9, 2) NULL,
			[pul20] [numeric](9, 2) NULL,
			[ver21] [numeric](9, 2) NULL,
			[pul21] [numeric](9, 2) NULL,
			[ver30] [numeric](9, 2) NULL,
			[pul30] [numeric](9, 2) NULL,
			[ver31] [numeric](9, 2) NULL,
			[pul31] [numeric](9, 2) NULL,
			[ver32] [numeric](9, 2) NULL,
			[pul32] [numeric](9, 2) NULL,
			[ver00] [numeric](9, 2) NULL,
			[pul00] [numeric](9, 2) NULL,
			[ver11] [numeric](9, 2) NULL,
			[pul11] [numeric](9, 2) NULL,
			[ver22] [numeric](9, 2) NULL,
			[pul22] [numeric](9, 2) NULL,
			[ver33] [numeric](9, 2) NULL,
			[pul33] [numeric](9, 2) NULL,
			[ver01] [numeric](9, 2) NULL,
			[pul01] [numeric](9, 2) NULL,
			[ver02] [numeric](9, 2) NULL,
			[pul02] [numeric](9, 2) NULL,
			[ver12] [numeric](9, 2) NULL,
			[pul12] [numeric](9, 2) NULL,
			[ver03] [numeric](9, 2) NULL,
			[pul03] [numeric](9, 2) NULL,
			[ver13] [numeric](9, 2) NULL,
			[pul13] [numeric](9, 2) NULL,
			[ver23] [numeric](9, 2) NULL,
			[pul23] [numeric](9, 2) NULL,
			[ver_ld] [numeric](9, 2) NULL,
			[pul_ld] [numeric](9, 2) NULL
		) ON [PRIMARY];
  END;
GO


