USE [TotDB]
IF OBJECT_ID('dbo.HistoryTotalsMT', 'U') IS NULL
    BEGIN
		CREATE TABLE [dbo].[HistoryTotalsMT]
		(
			[tirazhi ] [nvarchar](255) NULL,
			[data ] [datetime] NULL,
			[dzhek] [numeric](9, 5) NULL,
			[pul ] [numeric](9, 5) NULL,
			[slozhn] [numeric](9, 5) NULL,
			[maks vin] [numeric](9, 5) NULL,
			[kol_ var] [int] NULL,
			[kol_ unik] [int] NULL,
			[ver vin dzhek] [numeric](9, 5) NULL,
			[8 kol stav] [int] NULL,
			[8 sum stav] [numeric](9, 5) NULL,
			[8 rezult vypl] [numeric](9, 5) NULL,
			[7 kol stav] [int] NULL,
			[7 sum stav] [numeric](9, 5) NULL,
			[7 rezult vypl] [numeric](9, 5) NULL,
			[6 kol stav] [int] NULL,
			[6 sum stav] [numeric](9, 5) NULL,
			[6 rezult vypl] [numeric](9, 5) NULL,
			[5 kol stav] [int] NULL,
			[5 sum stav] [numeric](9, 5) NULL,
			[5 rezult vypl] [numeric](9, 5) NULL,
			[4 kol stav] [int] NULL,
			[4 sum stav] [numeric](9, 5) NULL,
			[4 rezult vypl] [numeric](9, 5) NULL,
			[3 kol stav] [int] NULL,
			[3 sum stav] [numeric](9, 5) NULL,
			[3 rezult vypl] [numeric](9, 5) NULL,
			[2 kol stav] [int] NULL,
			[2 sum stav] [numeric](9, 5) NULL,
			[2 rezult vypl] [numeric](9, 5) NULL,
			[sobyt] [int] NULL,
			[razdel] [nvarchar](255) NULL,
			[match ] [nvarchar](255) NULL,
			[schet] [nvarchar](10) NULL,
			[isxod] [nvarchar](10) NULL,
			[1:0 ver] [numeric](9, 2) NULL,
			[1:0 pul] [numeric](9, 2) NULL,
			[2:0 ver] [numeric](9, 2) NULL,
			[2:0 pul] [numeric](9, 2) NULL,
			[2:1 ver] [numeric](9, 2) NULL,
			[2:1 pul] [numeric](9, 2) NULL,
			[3:0 ver] [numeric](9, 2) NULL,
			[3:0 pul] [numeric](9, 2) NULL,
			[3:1 ver] [numeric](9, 2) NULL,
			[3:1 pul] [numeric](9, 2) NULL,
			[3:2 ver] [numeric](9, 2) NULL,
			[3:2 pul] [numeric](9, 2) NULL,
			[0:0 ver] [numeric](9, 2) NULL,
			[0:0 pul] [numeric](9, 2) NULL,
			[1:1 ver] [numeric](9, 2) NULL,
			[1:1 pul] [numeric](9, 2) NULL,
			[2:2 ver] [numeric](9, 2) NULL,
			[2:2 pul] [numeric](9, 2) NULL,
			[3:3 ver] [numeric](9, 2) NULL,
			[3:3 pul] [numeric](9, 2) NULL,
			[0:1 ver] [numeric](9, 2) NULL,
			[0:1 pul] [numeric](9, 2) NULL,
			[0:2 ver] [numeric](9, 2) NULL,
			[0:2 pul] [numeric](9, 2) NULL,
			[1:2 ver] [numeric](9, 2) NULL,
			[1:2 pul] [numeric](9, 2) NULL,
			[0:3 ver] [numeric](9, 2) NULL,
			[0:3 pul] [numeric](9, 2) NULL,
			[1:3 ver] [numeric](9, 2) NULL,
			[1:3 pul] [numeric](9, 2) NULL,
			[2:3 ver] [numeric](9, 2) NULL,
			[2:3 pul] [numeric](9, 2) NULL,
			[ld ver] [numeric](9, 2) NULL,
			[ld pul] [numeric](9, 2) NULL
		) ON [PRIMARY];
  END;
GO


