/*
        Tereshenko V.A. 08.06.2016
		Merge data from Stage
		
 USAGE:   
    exec dbo.HistoryTotalsMT_Merge

 check
    SELECT * FROM dbo.HistoryTotalsMT
	order by tirag, numb
	--delete FROM dbo.HistoryTotalsMT
	  
*/

IF OBJECT_ID('dbo.HistoryTotalsMT_Merge', 'P') IS NULL
    EXECUTE('CREATE PROCEDURE dbo.HistoryTotalsMT_Merge AS SELECT 1')

GO

ALTER PROCEDURE dbo.HistoryTotalsMT_Merge
AS
    BEGIN 
        SET NOCOUNT ON
        
        MERGE INTO dbo.HistoryTotalsMT AS Tdest
        USING
            ( SELECT    tirag ,
                        [data] ,
                        jackPot ,
                        [pool] ,
                        complex ,
                        maxWin ,
                        quanOption ,
                        quanUniq ,
                        winJack ,
                        quan8 ,
                        sum8 ,
                        res8 ,
                        quan7 ,
                        sum7 ,
                        res7 ,
                        quan6 ,
                        sum6 ,
                        res6 ,
                        quan5 ,
                        sum5 ,
                        res5 ,
                        quan4 ,
                        sum4 ,
                        res4 ,
                        quan3 ,
                        sum3 ,
                        res3 ,
                        quan2 ,
                        sum2 ,
                        res2 ,
                        numb ,
                        sect ,                       
                        account ,
                        exodus ,
                        prob10 ,
                        pool10 ,
                        prob20 ,
                        pool20 ,
                        prob21 ,
                        pool21 ,
                        prob30 ,
                        pool30 ,
                        prob31 ,
                        pool31 ,
                        prob32 ,
                        pool32 ,
                        prob00 ,
                        pool00 ,
                        prob11 ,
                        pool11 ,
                        prob22 ,
                        pool22 ,
                        prob33 ,
                        pool33 ,
                        prob01 ,
                        pool01 ,
                        prob02 ,
                        pool02 ,
                        prob12 ,
                        pool12 ,
                        prob03 ,
                        pool03 ,
                        prob13 ,
                        pool13 ,
                        prob23 ,
                        pool23 ,
                        probld ,
                        poolld
              FROM      Stage.HistoryTotalsMT
            ) AS Tsrc
        ON Tsrc.tirag = Tdest.tirag
		AND Tsrc.numb = Tdest.numb
		-- New attributes
        WHEN NOT MATCHED BY TARGET THEN
            INSERT ( tirag ,
                     [data] ,
                     jackPot ,
                     [pool] ,
                     complex ,
                     maxWin ,
                     quanOption ,
                     quanUniq ,
                     winJack ,
                     quan8 ,
                     sum8 ,
                     res8 ,
                     quan7 ,
                     sum7 ,
                     res7 ,
                     quan6 ,
                     sum6 ,
                     res6 ,
                     quan5 ,
                     sum5 ,
                     res5 ,
                     quan4 ,
                     sum4 ,
                     res4 ,
                     quan3 ,
                     sum3 ,
                     res3 ,
                     quan2 ,
                     sum2 ,
                     res2 ,
                     numb ,
                     sect ,                     
                     account ,
                     exodus ,
                     prob10 ,
                     pool10 ,
                     prob20 ,
                     pool20 ,
                     prob21 ,
                     pool21 ,
                     prob30 ,
                     pool30 ,
                     prob31 ,
                     pool31 ,
                     prob32 ,
                     pool32 ,
                     prob00 ,
                     pool00 ,
                     prob11 ,
                     pool11 ,
                     prob22 ,
                     pool22 ,
                     prob33 ,
                     pool33 ,
                     prob01 ,
                     pool01 ,
                     prob02 ,
                     pool02 ,
                     prob12 ,
                     pool12 ,
                     prob03 ,
                     pool03 ,
                     prob13 ,
                     pool13 ,
                     prob23 ,
                     pool23 ,
                     probld ,
                     poolld
                   )
            VALUES ( Tsrc.tirag ,
                     Tsrc.[data] ,
                     Tsrc.jackPot ,
                     Tsrc.[pool] ,
                     Tsrc.complex ,
                     Tsrc.maxWin ,
                     Tsrc.quanOption ,
                     Tsrc.quanUniq ,
                     Tsrc.winJack ,
                     Tsrc.quan8 ,
                     Tsrc.sum8 ,
                     Tsrc.res8 ,
                     Tsrc.quan7 ,
                     Tsrc.sum7 ,
                     Tsrc.res7 ,
                     Tsrc.quan6 ,
                     Tsrc.sum6 ,
                     Tsrc.res6 ,
                     Tsrc.quan5 ,
                     Tsrc.sum5 ,
                     Tsrc.res5 ,
                     Tsrc.quan4 ,
                     Tsrc.sum4 ,
                     Tsrc.res4 ,
                     Tsrc.quan3 ,
                     Tsrc.sum3 ,
                     Tsrc.res3 ,
                     Tsrc.quan2 ,
                     Tsrc.sum2 ,
                     Tsrc.res2 ,
                     Tsrc.numb ,
                     Tsrc.sect ,                     
                     Tsrc.account ,
                     Tsrc.exodus ,
                     Tsrc.prob10 ,
                     Tsrc.pool10 ,
                     Tsrc.prob20 ,
                     Tsrc.pool20 ,
                     Tsrc.prob21 ,
                     Tsrc.pool21 ,
                     Tsrc.prob30 ,
                     Tsrc.pool30 ,
                     Tsrc.prob31 ,
                     Tsrc.pool31 ,
                     Tsrc.prob32 ,
                     Tsrc.pool32 ,
                     Tsrc.prob00 ,
                     Tsrc.pool00 ,
                     Tsrc.prob11 ,
                     Tsrc.pool11 ,
                     Tsrc.prob22 ,
                     Tsrc.pool22 ,
                     Tsrc.prob33 ,
                     Tsrc.pool33 ,
                     Tsrc.prob01 ,
                     Tsrc.pool01 ,
                     Tsrc.prob02 ,
                     Tsrc.pool02 ,
                     Tsrc.prob12 ,
                     Tsrc.pool12 ,
                     Tsrc.prob03 ,
                     Tsrc.pool03 ,
                     Tsrc.prob13 ,
                     Tsrc.pool13 ,
                     Tsrc.prob23 ,
                     Tsrc.pool23 ,
                     Tsrc.probld ,
                     Tsrc.poolld
                   );

    END 